params={
    'enc_type': 'lstm',
    'dec_type': 'lstm',
    'nz': 32,
    'ni': 128,
    'enc_nh': 512,
    'dec_nh': 512,
    'log_niter': 50,
    'dec_dropout_in': 0.5,
    'dec_dropout_out': 0.5,
    'batch_size': 32,
    'epochs': 100,
    'test_nepoch': 5,
    'train_data': 'datasets/tatoeba2_data/tatoeba.train.txt',
    'train_data_en': 'datasets/tatoeba2_data/tatoeba.train.en.txt',
    'val_data_en': 'datasets/tatoeba2_data/tatoeba.valid.en.txt',
    'test_data_en': 'datasets/tatoeba2_data/tatoeba.test.en.txt',
    'train_data_fr': 'datasets/tatoeba2_data/tatoeba.train.fr.txt',
    'val_data_fr': 'datasets/tatoeba2_data/tatoeba.valid.fr.txt',
    'test_data_fr': 'datasets/tatoeba2_data/tatoeba.test.fr.txt',
    'ais_prior': 'normal',
    'ais_T': 500,
    'ais_K': 3,
    "label": False
}
